name: âš¡ï¸ Update Status âš¡ï¸

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ğŸ
        continue-on-error: true
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Clone the Repo ğŸŒ€
        continue-on-error: true
        uses: actions/checkout@master
        with:
          repository: filteradmin/botstatus
      - name: Install Requirements ğŸ“€
        continue-on-error: true
        run: |
          pip install --upgrade pip
          pip install wget pytz telethon python-dotenv
      - name: Run the User Client ğŸƒâ€â™‚ï¸
        continue-on-error: true
        run: |
          python3 main.py
        env:
          CONFIG: ${{ secrets.CONFIG }}
